Repository raphaelmor/Polyline, pull requests merged in 2020-11, with the labels that each got.

#63 Increase minimum deployment targets.
  Polyline.podspec
  Polyline.xcodeproj/project.pbxproj
  README.md
Labels: backwards-incompatible, build

#57 Swift 5
  .swift-version
  .travis.yml
  Polyline.podspec
  Polyline.xcodeproj/project.pbxproj
  Polyline.xcodeproj/xcshareddata/xcschemes/Polyline.xcscheme
  Polyline.xcodeproj/xcshareddata/xcschemes/PolylineMac.xcscheme
  Polyline.xcodeproj/xcshareddata/xcschemes/PolylineTV.xcscheme
  Polyline.xcodeproj/xcshareddata/xcschemes/PolylineWatch.xcscheme
Labels: build

#55 Add support for Linux
  .travis.yml
  .travis/build.sh
  README.md
  Sources/Polyline/CoreLocation.swift
  Sources/Polyline/Polyline.swift
  Tests/LinuxMain.swift
  Tests/PolylineTests/FunctionalPolylineTests.swift
  Tests/PolylineTests/PolylineTests.swift
  Tests/PolylineTests/XCTestManifests.swift
Labels: build, enhancement

#64 Enable library evolution
  Polyline.xcodeproj/project.pbxproj
Labels: backwards-incompatible, build

#65 v5.0.0
  Polyline.podspec
  Polyline.xcodeproj/project.pbxproj
  README.md
  Sources/Polyline/Info.plist
  Tests/PolylineTests/Info.plist
Labels: build

#67 Fix watchOS compiler error about MapKit
  .travis/build.sh
  Sources/Polyline/Polyline.swift
Labels: bug, build

#69 Make CLLocationCoordinate2D properties public on Linux
  Sources/Polyline/CoreLocation.swift
Labels: bug

#70 v5.0.1
  Polyline.podspec
  Polyline.xcodeproj/project.pbxproj
  README.md
  Sources/Polyline/Info.plist
  Tests/PolylineTests/Info.plist
Labels: build

#71 Modernize buffer access
  Sources/Polyline/Polyline.swift
  Tests/PolylineTests/FunctionalPolylineTests.swift
  Tests/PolylineTests/XCTestManifests.swift
Labels: bug

#72 v5.0.2
  Polyline.podspec
  Polyline.xcodeproj/project.pbxproj
  README.md
  Sources/Polyline/Info.plist
  Tests/PolylineTests/Info.plist
Labels: build
